# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 507)
        Dialog.setStyleSheet("/* DIALOG BG COLOR */\n"
"\n"
"#Dialog {\n"
"   background-color: #800000;\n"
"}\n"
"\n"
"#infoFRAME {\n"
"  background-color:  #FFD700;\n"
"padding: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #800000;  /* Yellow Text */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 2px solid #800000;  /* Yellow Border */\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #FFD700; /* Yellow */\n"
"    color: #800000;\n"
"    font-weight: bold;\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFC107; /* Slightly Darker Yellow on Hover */\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 2px solid #FFD700;  /* Yellow Border */\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: none;\n"
"    color: #800000; /* Change text color if needed */\n"
"}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.infoFRAME = QtWidgets.QFrame(Dialog)
        self.infoFRAME.setMinimumSize(QtCore.QSize(0, 451))
        self.infoFRAME.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFRAME.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFRAME.setObjectName("infoFRAME")
        self.gridLayout = QtWidgets.QGridLayout(self.infoFRAME)
        self.gridLayout.setObjectName("gridLayout")
        self.studentid = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.studentid.setFont(font)
        self.studentid.setObjectName("studentid")
        self.gridLayout.addWidget(self.studentid, 0, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.firstname = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.firstname.setFont(font)
        self.firstname.setObjectName("firstname")
        self.gridLayout.addWidget(self.firstname, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_10.setReadOnly(False)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 1, 1, 1, 1)
        self.lastname = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.lastname.setFont(font)
        self.lastname.setObjectName("lastname")
        self.gridLayout.addWidget(self.lastname, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_11.setReadOnly(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.sex = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.sex.setFont(font)
        self.sex.setObjectName("sex")
        self.gridLayout.addWidget(self.sex, 3, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_14.setReadOnly(False)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 3, 1, 1, 1)
        self.age = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.gridLayout.addWidget(self.age, 4, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_12.setReadOnly(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 4, 1, 1, 1)
        self.program = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.program.setFont(font)
        self.program.setObjectName("program")
        self.gridLayout.addWidget(self.program, 5, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.infoFRAME)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.yearlevel = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.yearlevel.setFont(font)
        self.yearlevel.setObjectName("yearlevel")
        self.gridLayout.addWidget(self.yearlevel, 6, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_13.setReadOnly(False)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 6, 1, 1, 1)
        self.college = QtWidgets.QLabel(self.infoFRAME)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        self.college.setFont(font)
        self.college.setObjectName("college")
        self.gridLayout.addWidget(self.college, 7, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.infoFRAME)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 7, 1, 1, 1)
        self.gridLayout_2.addWidget(self.infoFRAME, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.studentid.setText(_translate("Dialog", "STUDENT ID #"))
        self.firstname.setText(_translate("Dialog", "FIRST NAME"))
        self.lastname.setText(_translate("Dialog", "LAST NAME"))
        self.sex.setText(_translate("Dialog", "SEX"))
        self.age.setText(_translate("Dialog", "AGE"))
        self.program.setText(_translate("Dialog", "PROGRAM"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "N/A"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "BSBIO-BOT - BS Biology (Botany)"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "BSBIO-ZOO - BS Biology (Zoology)"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "BSMATH - BS Mathematics"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "BSCS - BS Computer Science"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "BSIT - BS Information Technology"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "BSIS - BS Information Systems"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "BSCHE - BS Chemical Engineering"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "BSCE - BS Civil Engineering"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "BSCPE - BS Computer Engineering"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "BSEE - BS Electrical Engineering"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "BSECE - BS Electronics and Communication Engineering"))
        self.comboBox_2.setItemText(12, _translate("Dialog", "BAELS - BA English Language Studies"))
        self.comboBox_2.setItemText(13, _translate("Dialog", "BAFIL - BA Filipino"))
        self.comboBox_2.setItemText(14, _translate("Dialog", "BAPOLSCI - BA Political Science"))
        self.comboBox_2.setItemText(15, _translate("Dialog", "BAPSY - BA Psychology"))
        self.comboBox_2.setItemText(16, _translate("Dialog", "BSPSY - BS Psychology"))
        self.comboBox_2.setItemText(17, _translate("Dialog", "BSEDBIO - BSED Biology"))
        self.comboBox_2.setItemText(18, _translate("Dialog", "BSEDCHEM - BSED Chemistry"))
        self.comboBox_2.setItemText(19, _translate("Dialog", "BSEDPHYS - BSED Physics"))
        self.comboBox_2.setItemText(20, _translate("Dialog", "BSEDMATH - BSED Mathematics"))
        self.comboBox_2.setItemText(21, _translate("Dialog", "BPED - Bachelor of Physical Education"))
        self.comboBox_2.setItemText(22, _translate("Dialog", "BSA - BS Accountancy"))
        self.comboBox_2.setItemText(23, _translate("Dialog", "BSBA-BE - BSBA in Business Economics"))
        self.comboBox_2.setItemText(24, _translate("Dialog", "BSHM - BS Hospitality Management"))
        self.comboBox_2.setItemText(25, _translate("Dialog", "BSN - BS Nursing"))
        self.yearlevel.setText(_translate("Dialog", "YEAR LEVEL"))
        self.college.setText(_translate("Dialog", "COLLEGE"))
