# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFINALE.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1016, 664)
        Form.setStyleSheet("/* Styles for the titleFrame element */\n"
"#titleFrame {\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"/* TEXT SIZE AND COLOR */\n"
"QLabel {\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 2px;\n"
"}\n"
"\n"
"\n"
"/* FORM FRAME */\n"
"#Form { \n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #800000, /* Dark Maroon */\n"
"                                stop:1 #A52A2A); /* Brownish Maroon */\n"
"    color: black;\n"
"}\n"
"\n"
"\n"
"/* INFO FRAME BG COLOR */\n"
"#infoFrame {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FFD54F, stop:1 #FFB300);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    color: #800000;  /* Yellow Text */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 2px solid #800000;  /* Yellow Border */\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"/* INPUT FIELDS HEIGHT */\n"
"QLineEdit, QComboBox {\n"
"    height: 25px;\n"
"    border-radius: 5px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"\n"
"/* Styles for the functionFrame and its elements */\n"
"#functionFrame {\n"
"  background-color: transparent;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"/* FOR PUSH BUTTONS */\n"
"\n"
"/* Buttons with Yellow Background and White Text */\n"
"QPushButton {\n"
"     background-color: #FFC107; /* Yellow */\n"
"    color: #800000;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Hover effect for buttons (Darker Yellow) */\n"
"QPushButton:hover {\n"
"    background-color: #FFA000; /* Darker Amber Yellow */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QComboBox {\n"
"  color: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: none;\n"
"    color: #800000; /* Change text color if needed */\n"
"}\n"
"\n"
"\n"
"\n"
"/* TABLE */\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #FFC107;  /* Goldish Yellow */\n"
"    color: #800000;             /* Maroon Text */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"    border: 1px solid #800000;  /* Maroon Border */\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;       /* Clean base */\n"
"    alternate-background-color: #FFEBB5;  /* Soft pastel yellow */\n"
"    gridline-color: #800000;        /* Maroon grid */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: black;              /* Text should be readable */\n"
"    font-size: 13px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background: #FFD54F; /* Same as header */\n"
"    color: black;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #800000; /* Deep red (highlights selected row) */\n"
"    color: white;              /* White text for readability */\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white; /* Match your form\'s background */\n"
"    gridline-color: #dark-yellow;\n"
"    alternate-background-color: #yellow;\n"
"}\n"
"QTableWidget::item {\n"
"    background-color: #yellow;\n"
"}\n"
"QTableWidget::item:alternate {\n"
"    background-color: #dark-yellow;\n"
"}\n"
"")
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.titleFrame = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.titleFrame.setFont(font)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.titleFrame)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(-1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFC107;")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout_5.addWidget(self.titleFrame, 0, 0, 1, 1)
        self.infoFrame = QtWidgets.QFrame(Form)
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.infoFrame)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #800000;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.infoFrame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #800000;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.infoFrame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #800000;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.infoFrame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #800000;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.infoFrame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #800000;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.infoFrame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #800000;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.infoFrame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #800000;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.infoFrame)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.infoFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #800000;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.infoFrame)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.infoFrame, 1, 0, 1, 1)
        self.functionFrame = QtWidgets.QFrame(Form)
        self.functionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.functionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.functionFrame.setObjectName("functionFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.functionFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.functionFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/add_24dp_800000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.functionFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/refresh_24dp_800000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.functionFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/delete_24dp_800000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.functionFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_5.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/backspace_24dp_800000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.functionFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/edit_24dp_800000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 0, 5, 1, 1)
        self.gridLayout_5.addWidget(self.functionFrame, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/visibility_24dp_800000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #FFC107;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.gridLayout_5.addWidget(self.frame_5, 3, 0, 1, 1)
        self.tableFrame = QtWidgets.QFrame(Form)
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableFrame.setObjectName("tableFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tableFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tableFrame)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.tableFrame, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Student Information System</p></body></html>"))
        self.label_2.setText(_translate("Form", "STUDENT ID #"))
        self.label_3.setText(_translate("Form", "FIRST NAME"))
        self.label_4.setText(_translate("Form", "LAST NAME"))
        self.label_5.setText(_translate("Form", "AGE"))
        self.label_6.setText(_translate("Form", "SEX"))
        self.comboBox.setItemText(0, _translate("Form", "N/A"))
        self.comboBox.setItemText(1, _translate("Form", "MALE"))
        self.comboBox.setItemText(2, _translate("Form", "FEMALE"))
        self.label_7.setText(_translate("Form", "PROGRAM"))
        self.comboBox_2.setItemText(0, _translate("Form", "N/A"))
        self.comboBox_2.setItemText(1, _translate("Form", "BSBIO-BOT - BS Biology (Botany)"))
        self.comboBox_2.setItemText(2, _translate("Form", "BSBIO-ZOO - BS Biology (Zoology)"))
        self.comboBox_2.setItemText(3, _translate("Form", "BSMATH - BS Mathematics"))
        self.comboBox_2.setItemText(4, _translate("Form", "BSCS - BS Computer Science"))
        self.comboBox_2.setItemText(5, _translate("Form", "BSIT - BS Information Technology"))
        self.comboBox_2.setItemText(6, _translate("Form", "BSIS - BS Information Systems"))
        self.comboBox_2.setItemText(7, _translate("Form", "BSCHE - BS Chemical Engineering"))
        self.comboBox_2.setItemText(8, _translate("Form", "BSCE - BS Civil Engineering"))
        self.comboBox_2.setItemText(9, _translate("Form", "BSCPE - BS Computer Engineering"))
        self.comboBox_2.setItemText(10, _translate("Form", "BSEE - BS Electrical Engineering"))
        self.comboBox_2.setItemText(11, _translate("Form", "BSECE - BS Electronics and Communication Engineering"))
        self.comboBox_2.setItemText(12, _translate("Form", "BAELS - BA English Language Studies"))
        self.comboBox_2.setItemText(13, _translate("Form", "BAFIL - BA Filipino"))
        self.comboBox_2.setItemText(14, _translate("Form", "BAPOLSCI - BA Political Science"))
        self.comboBox_2.setItemText(15, _translate("Form", "BAPSY - BA Psychology"))
        self.comboBox_2.setItemText(16, _translate("Form", "BSPSY - BS Psychology"))
        self.comboBox_2.setItemText(17, _translate("Form", "BSEDBIO - BSED Biology"))
        self.comboBox_2.setItemText(18, _translate("Form", "BSEDCHEM - BSED Chemistry"))
        self.comboBox_2.setItemText(19, _translate("Form", "BSEDPHYS - BSED Physics"))
        self.comboBox_2.setItemText(20, _translate("Form", "BSEDMATH - BSED Mathematics"))
        self.comboBox_2.setItemText(21, _translate("Form", "BPED - Bachelor of Physical Education"))
        self.comboBox_2.setItemText(22, _translate("Form", "BSA - BS Accountancy"))
        self.comboBox_2.setItemText(23, _translate("Form", "BSBA-BE - BSBA in Business Economics"))
        self.comboBox_2.setItemText(24, _translate("Form", "BSHM - BS Hospitality Management"))
        self.comboBox_2.setItemText(25, _translate("Form", "BSN - BS Nursing"))
        self.label_8.setText(_translate("Form", "YEAR LEVEL"))
        self.label_9.setText(_translate("Form", "COLLEGE"))
        self.pushButton.setText(_translate("Form", "ADD"))
        self.pushButton_3.setText(_translate("Form", "UPDATE"))
        self.pushButton_4.setText(_translate("Form", "DELETE"))
        self.pushButton_5.setText(_translate("Form", "CLEAR"))
        self.pushButton_6.setText(_translate("Form", "EDIT"))
        self.pushButton_2.setText(_translate("Form", "READ"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\">L I S T</p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "STUDENT ID #"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "FIRST NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "LAST NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "AGE"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "SEX"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "PROGRAM"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "YEAR LEVEL"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "COLLEGE"))
